config/routes.rb
Blueboxes::Application.routes.draw do

  root :to => 'admin#index'
  resources :comments
  resources :signups
  resources :pictures
  resources :areas
  resources :schedules
  resources :locations
  resources :shifts
  get 'volunteers/email' => 'volunteers#email'
  resources :volunteers
  get 'prefs' => 'prefs#index'
  get 'volunteers/prefs' => 'volunteers#prefs'
  match 'volunteers/edit_pw/:id' => 'volunteers#edit_pw'
  match 'volunteers/print_list' => 'volunteers#print_list'
  match 'home/set_vol/:id/:schedule' => 'home#set_vol'
  get 'home' => 'admin#index'
  get 'home/slotPerson2' => 'home#slotPerson2'
  get 'home/slots/:schedule' => 'home#slots'
  get 'gate/duties' => 'gate#message'
  get 'admin/index' => 'admin#index'
  match 'admin/login' => 'admin#login'
  match 'admin/logout' => 'admin#logout'
  get 'admin/bkup' => 'admin#bkup'
  get 'admin/stats' => 'admin#stats'
  match 'admin/set_area/:id' => 'admin#set_area'
  match 'admin/unset_area' => 'admin#unset_area'
  get 'admin/profile' => 'admin#profile'
  get 'gallery' => 'gallery#index'
  get 'gallery/picture/:id' => 'gallery#picture'
  get 'schedules/duplicate/:id' => 'schedules#duplicate'
  post 'schedules/copy/:id' => 'schedules#copy'
  match 'schedules/assign/:id' => 'schedules#assign'
  get 'schedules/print/:id' => 'schedules#print'
  get 'schedules/save/:id' => 'schedules#save'
  get 'schedules/save2/:id' => 'schedules#save2'
  get 'schedules/print2/:id' => 'schedules#print2'
  match 'schedules/update_shift/:id/:vol' => 'schedules#update_shift'
  match 'schedules/do_work/:id' => 'schedules#do_work'
  match 'schedules/do_jswork/:id' => 'schedules#do_jswork'
  match 'news' => 'news#index'
  match 'news/new_entry' => 'news#new_entry'


  #map.connect "home/assign/:schedule", :controller => 'home', :action => 'assign'
  #map.connect "gate/duties", :controller => 'gate', :action => 'duties'


  # See how all your routes lay out with "rake routes"

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :area
  has_many :shifts, :dependent=>:destroy, :order=>"start, location_id"
  has_and_belongs_to_many :locations
  has_many :volunteers
  validates_presence_of :start, :area_id

  after_create :create_shifts
  
  @@slots_per_day=[[12,14,16,18], [8,10,12,14,16,18,20],[8,10,12,14,16,18,20],[8,10,12,14,16,18,20],[9,11,13]]

  attr_accessor :pending


  def self.slots_per_day
	@@slots_per_day
  end 
  def add_shift(shift)
     @shifts << shift
  end

  # sets both shifttimes and shifttimes_per_day which is similar to slots_per_day but tailored to the schedule. Eg Parking2013 schedule started at 2, not noon.
  def shifttimes
    if @shifttimes.nil?
	setshifttimes
    end
    @shifttimes
  end

  def shifttimes=
	@shifttimes=[]
	@@slots_per_day.each_with_index  do |d, i|
	    n=(self.start+i).to_time
	    d.each do |t|
		    @shifttimes<< n+(t*3600)
	    end
	end
  end   
  def shifttimes_per_day
    if @shifttimes_per_day.nil?
	setshifttimes
    end
    @shifttimes_per_day
  end
  def shifttimes_per_day=(st)
	@shifttimes_per_day=st
  end
  def setshifttimes
	@shifttimes=[]
	@shifttimes_per_day=@@slots_per_day
 	if self.year < 2014
		@shifttimes_per_day[0]=[14,16,18]
	end
	@shifttimes_per_day.each_with_index  do |d, i|
	    n=(self.start+i).to_time
	    d.each do |t|
		    @shifttimes<< n+(t*3600)
	    end
	end
  end   

  def add_location(loc)
	  return if self.locations.include?(loc)
	  self.locations << loc 
          st=getshifttimes
          st.each do |t|
		shift=Shift.new
		shift.location=loc
		shift.start=t
		self.shifts << shift
	  end
    end
  
  protected
  # to be done after locations is set
  def create_shifts
	self.shifts=[]
	if self.locations.size==0
	  self.locations=self.area.locations
	end
	st=self.shifttimes  
    	st.each do |t|
		self.locations.each do |l|
		
			shift=Shift.new
			shift.location=l
			shift.start=t
			self.shifts << shift
		end
    	end
  end
  
  
  
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	before_filter :check_admin, :except=>['index', 'show', 'print', 'print2', 'save','save2']
	
	#caches_page :show
  # GET /schedules
  # GET /schedules.xml
  attr_accessor :worker

  def index
    @schedules = Schedule.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.xml
  def show
	@schedule = Schedule.find(params[:id])
	#if @schedule.start != @schedule.shifts[0].start then
	#	#flash[:notice]="Warning: schedule starts at ", @schedule.start.to_s," but shifts start at ",@schedule.shifts[0].start.to_s
	#end
	@shift_days=@schedule.shifts.group_by{|x| x.start.day}
	@shifts=@schedule.shifts.to_a.sort_by!{|x| [x.start, x.location]}
	@locations=Location.where(:area_id => @schedule.area_id)
	@x=@locations.size + 1
	@n_assigned=0
	@schedule.shifts.each{|x| @n_assigned+=1 if x.volunteer}
	
	@ppl_sh=@schedule.shifts.group_by{|v| v.volunteer}
	@ppl_sh.delete(nil)
	@ppl_sh_s=@ppl_sh.keys.sort_by{|x| [x.hat.to_s,x.name]}
	@tms=@schedule.shifttimes
	puts "*****shifttimes: "+@schedule.shifttimes.to_s
    respond_to do |format|
      format.html # show.html.erb 
     
      format.xml  { render :xml => @schedule }
    end
    
  end
    
  def print
	@schedule = Schedule.find(params[:id])
	#if @schedule.start != @schedule.shifts[0].start then
	#	#flash[:notice]="Warning: schedule starts at ", @schedule.start.to_s," but shifts start at ",@schedule.shifts[0].start.to_s
	#end
	@shift_days=@schedule.shifts.group_by{|x| x.start.day}
	@shifts=@schedule.shifts.to_a.sort_by!{|x| [x.start, x.location]}
	@locations=Location.where(:area_id => @schedule.area_id)
	@x=@locations.size + 1
	@n_assigned=0
	@schedule.shifts.each{|x| @n_assigned+=1 if x.volunteer}
	
	@ppl_sh=@schedule.shifts.group_by{|v| v.volunteer}
	@ppl_sh.delete(nil)
	@ppl_sh_s=@ppl_sh.keys.sort_by{|x| [x.hat.to_s,x.name]}
	@tms=@schedule.shifttimes
	render(:layout => 'print')
 end
 def print2
	@schedule = Schedule.find(params[:id])
	if @schedule.start != @schedule.shifts[0].start then
	   #flash[:error]="wrong begin date"
	end
       
	@shift_days=@schedule.shifts.group_by{|x| x.start.day}
	#@x=Location.count+1 # wrong... this gets all of them
	@locations=Location.where(:area_id => @schedule.area_id)
	@x=@locations.size + 1
	
	@n_assigned=0
	@schedule.shifts.each{|x| @n_assigned+=1 if x.volunteer}
	
	@ppl_sh=@schedule.shifts.group_by{|v| v.volunteer}
	@ppl_sh.delete(nil)
	@ppl_sh_s=@ppl_sh.keys.sort_by{|x| [x.hat.to_s,x.name]}
	@tms=@schedule.shifttimes
	 
	 render(:layout => 'print')
  end
  def save
	@schedule = Schedule.find(params[:id])
	if @schedule.start != @schedule.shifts[0].start then
	   #flash[:error]="wrong begin date"
	end
       
	@shift_days=@schedule.shifts.group_by{|x| x.start.day}
	#@x=Location.count+1 # wrong... this gets all of them
	@locations=Location.where(:area_id => @schedule.area_id)
	@x=@locations.size + 1
	@n_assigned=0
	@schedule.shifts.each{|x| @n_assigned+=1 if x.volunteer}
	
	@ppl_sh=@schedule.shifts.group_by{|v| v.volunteer}
	@ppl_sh.delete(nil)
	@ppl_sh_s=@ppl_sh.keys.sort_by{|x| [x.hat.to_s,x.name]}
	@tms=@schedule.shifttimes
	 headers['Content-Type'] = "application/vnd.ms-excel"
    headers['Content-Disposition'] = 'attachment; filename="BSParking#{@schedule.year}-keys.xls"'
    headers['Cache-Control'] = ""

	 render(:layout => 'print')
 end
 def save2
	@schedule = Schedule.find(params[:id])
	if @schedule.start != @schedule.shifts[0].start then
	   #flash[:error]="wrong begin date"
	end
       
	@shift_days=@schedule.shifts.group_by{|x| x.start.day}
	#@x=Location.count+1 # wrong... this gets all of them
	@locations=Location.find_all_by_area_id(@schedule.area_id)
	@x=@locations.size + 1
	@n_assigned=0
	@schedule.shifts.each{|x| @n_assigned+=1 if x.volunteer}
	
	@ppl_sh=@schedule.shifts.group_by{|v| v.volunteer}
	@ppl_sh.delete(nil)
	@ppl_sh_s=@ppl_sh.keys.sort_by{|x| [x.hat.to_s,x.name]}
	@tms=@schedule.shifttimes
	 headers['Content-Type'] = "application/vnd.ms-excel"
    headers['Content-Disposition'] = 'attachment; filename="BSParking2013-keys.xls"'
    headers['Cache-Control'] = ""

	 render(:layout => 'print')
 end
  # GET /schedules/new
  # GET /schedules/new.xml
  def new
    @schedule = Schedule.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.xml
  def create
    @schedule = Schedule.new(params[:schedule])
    @schedule.locations=Location.where( {area_id: @schedule.area })

	
    respond_to do |format|
      if @schedule.save
        flash[:notice] = 'Schedule was successfully created.'
        format.html { redirect_to(@schedule) }
        format.xml  { render :xml => @schedule, :status => :created, :location => @schedule }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end
 
  
  # PUT /schedules/1
  # PUT /schedules/1.xml
  def update
    @schedule = Schedule.find(params[:id])
    
    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
	 expire_page :action => 'show', :id => params[:id]
        flash[:notice] = 'Schedule was successfully updated.'
        format.html { redirect_to(@schedule) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.xml
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to(schedules_url) }
      format.xml  { head :ok }
    end
  end
  
  def set_locations
	  @schedule=Schedule.find(params[:id])
	  @locations=@schedule.locations
	  if request.post?
		  nlist=params[:locations]
		  nlist.each do |x|
			  l=Location.find(x)
			  @schedule.add_location(l)
		  end
		  
	  end
	  
  end
  
  #GET schedules/assign/1 for the volunteer to assign; POST for the table
def assign

	@id=params[:id]
	@schedule=Schedule.find(@id)
	if @schedule.nil?
		flash[:notice]="No schedule by the name: " && params[:schedule]
		@schedule=Schedule.last
		return
	end
	@area=@schedule.area
	if @area.nil?
		flash[:error]="No area set for the schedule"
		return
	end
	@shifts=@schedule.shifts.to_a
	@volunteers=@area.volunteers.to_a
	if @volunteers.empty?
		flash[:error]="No volunteers for this area. Please edit some volunteers."
		return
	end
	taskData=session[:taskData]
	if !taskData.nil?
		flash[:error]="Save failed. Logout and restart browser"
	end
	@pending=taskData
	if request.post?
		@volunteer = Volunteer.find(params[:vol])
	else
		@volunteer=Volunteer.find(session[:update_vol]) if session[:update_vol]
		varea=@volunteer.area
		@volunteer=nil if (varea.nil?||(varea.id != @area.id))
	end	
	
	if @volunteer.nil? 
		@volunteer=@volunteers[0]||Volunteer.find(2)
	end
	@vname=@volunteer.name
	session[:update_vol]=@volunteer.id
	
	@shift_days=@shifts.group_by{|x| x.start.day}
	@locations=Location.where(:area_id => @schedule.area_id)
	@x=@locations.size + 1
	# count the total number of shifts assigned in the schedule
	@assigned=Hash.new 0
	vol_shifts=Hash.new []
	puts "shift size *** "+@shifts.length.to_s
	@shifts.each do |s|
		v=s.volunteer_id
		if !v.nil?
		@assigned[v]+=1
		vol_shifts[v] << s.id
		end
	end
	@n_shifts=@assigned[@volunteer.id]
	@n_assigned = @assigned.values.sum
	#
	# get signed up volunteers by year, get all volunteers in an area
	# intersection is the list of volunteers for that schedule
	vol_by_year=Signup.where(:year => @schedule.year).map{|x| x.volunteer_id}
	 vol_by_area=@area.volunteers.map{|x| x.id}
	 vols=vol_by_year & vol_by_area
	@arvols=Volunteer.find(vols)
	@vol_info=@arvols.map{|i| [i.id, i.name, @assigned[i.id]||0, i.signups.last.early, i.restrictions]}
	@droplist=@arvols.map{|i| [i.name, i.id]}
  end
  
  # called when assigning a shift by the button click
  def update_shift
	sh = Shift.find(params[:id])
 	@schedule=sh.schedule
    	vol = Volunteer.find(params[:vol])

	session[:work].tasks<<[params[:id],params[:vol]]
	redirect_to :action => 'assign', :id => sh.schedule.id, :vol=> vol
   end
	
   # post /schedules/do_jswork request comes from javascript buttons.js when
   # user clicks the save/work button on the assign page
   def do_jswork
	@id=params[:id]
        if @id == 0 
		flash[:notice] = 'Schedule cancelled updates.'
		render js: %(window.location.pathname='/schedules/assign/#{@id}')
		return
	end
	taskData = request.body.read
	puts "In controller do_jswork: post data: "+taskData
	vol=session[:update_vol]
	worker=Worker.new(@id,session[:volunteer_id])
	worker.tasks=taskData
	if worker.tasks.nil? 
		puts "In controller do_jswork action, but there's nothing to do"
	else
		puts "In controller do_jswork action. "+worker.tasks.to_s()
		worker.do_work()
	end
	session[:taskData]=nil
	expire_page :action => 'show', :id => @id
        flash[:notice] = 'Schedule was successfully updated.'
	# need to render js because it won't refresh if just render html
	render js: %(window.location.pathname='/schedules/assign/#{@id}')
   end

#GET schedules/1/duplicate
def duplicate
	   #flash[:notice] = params.keys << " values: " << params.values
	   
    @old = Schedule.find(params[:id])
    session[:cid]=@old.id
    
    @schedule = Schedule.new
    @schedule.area_id=@old.area_id
    @schedule.year=@old.year+1
    @schedule.shiftlength=@old.shiftlength
    days_in_year=365
    days_in_year=366 if (@old.start.year+1).modulo(4)==0
	days_in_year=364 # for 2013
    @schedule.start=@old.start+days_in_year
    @schedule.end=@old.end+days_in_year
    @schedule.title = "Copy of " <<@old.title

app/helpers/schedules_helper.rb
module SchedulesHelper

 def timeheader(tms)
    boxes=Schedule.slots_per_day
    currentday=tms[0]
    @content = content_tag(:tr, class: "days") do
	concat content_tag(:td, tms[0].year, class: "names")
 	boxes.each do |b|
	   concat "<td colspan='#{b.size}'>#{currentday.strftime("%a")}</td>".html_safe
	   currentday=(currentday + 1.day)
	end
    end
    @content << "<tr><td></td>".html_safe
    tms.each do |t|
	@content << content_tag(:td, t.strftime("%l%p").downcase, class: "times") 
    end
    @content
 end
 def status(y)
	 return "draft" if y==0
	 return "review" if y==1
	 return "final" if y==2
 end
 def utc(t)
	return "y" if t.utc?
	return "n"
 end
 
 def vol_row(v,shfs,tms)
	if v==nil
	 return "nil" 
	 end
	name=v.name
	@content = "<tr>".html_safe
	@content << content_tag(:td, name, class: "sched")

	i=0
	if shfs==nil
	return 
	end
	
	 shfs.each do |k| 
		 while tms[i] < k.start && i <tms.size-1
				@content << "<td></td>".html_safe
				i+=1
		end
		@content << content_tag(:td, k.location.name)
		i+=1
	end
	
	while i<tms.size do
		@content << content_tag(:td, '')
		i+=1
	end
	
	@content << "</tr>".html_safe
	@content
end
def cell_color(sh)
	
	if flash[:bad_cells]==sh.id
	return "red"
	end
	
end
end

app/views/schedules/duplicate.html.erb
<h1>Duplicate schedule</h1>

<%= form_for(@schedule, :url => { :action => "copy" })  do |f| %>
 <% @schedule.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
   <% end %>


  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :year %><br />
    <%= f.select :year, [2011,2012,2013,2014] %>
  </p>
  <p>
  Hat Area: <br/>
  <%=area_choices("schedule") %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows=>4%>
  </p>
  <p>
    <%= f.label :start %><br />
    <%= f.date_select :start%>
  </p>
  <p>
    <%= f.label :end %><br />
    <%= f.date_select :end%>
  </p>
  <p>
    <%= f.label :shiftlength %><br />
    <%= f.text_field :shiftlength, :size=>'2', :disabled=>'disabled'%>&nbsp;hours
    <%= hidden_field :schedule, :shiftlength%>
  </p>
  <p>
    <%= f.submit 'Copy' %>
  </p>
<% end %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= form_for(@schedule) do |f| %>
 <% @schedule.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
   <% end %>


  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    Year<br />
    <%= f.select :year, [2011,2012,2013,2014,2015,2106]%>
  </p>
  <p>
    Status<br />
    <%= f.select :status, [["draft",0],["review",1],["final",2]]%>
  </p>
  <p>
  Hat Area: <br/>
  <%=area_choices("schedule") %>
  </p>
  <p>
    <%= f.label :description %><br />
     <%= f.text_area :description, :rows=>4%>
  </p>
  <p>
    <%= f.label :start %><br />
    <%= f.date_select :start %>
  </p>
  <p>
    <%= f.label :end %><br />
    <%= f.date_select :end %>
  </p>
  <p>
    <%= f.label :shiftlength %><br />
    <%= f.select(:shiftlength, [2,3,4,5]) %>hours
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <tr>
  <th>Id</th>
    <th>Title</th>
     <th>Domain</th>
    <th>Year</th>
    <th>Status</th>
    <th>Description</th>
    <th>Start</th>
    <th>End</th>
    <th>Shiftlength</th>
  </tr>

<% @schedules.each do |schedule| %>
  <tr>
  <td><%=h schedule.id %></td>
    <td><%=h schedule.title %></td>
      <td><%=h schedule.area.name %></td>
     <td><%=h schedule.year %></td>
    <td><%=h status(schedule.status) %></td>
    <td><%=h truncate(schedule.description) %></td>
    <td><%=h schedule.start.strftime("%a, %B %d, %Y") %></td>
    <td><%=h schedule.end.strftime("%a, %B %d, %Y") %></td>
    <td><%=h schedule.shiftlength %></td>
    <td><%= link_to 'Show', schedule %></td>
    <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
    <td><%= link_to 'Duplicate', url_for(:action=>'duplicate', :id=>schedule.id)%></td>
      <% if schedule.status!=2 %>  <td><%= link_to 'Assign Shifts', url_for(:action=> 'assign', :id=>schedule.id)%></td><% end %>
    <% if schedule.status==0 %>    <td><%= button_to 'Destroy', schedule, :method => :delete,  :onclick => "return confirm('Are you sure?')" %></td> <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<div id="outer">
<div id="inner">
<h1>New schedule</h1>

<%= form_for(@schedule) do |f| %>
 <% @schedule.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
   <% end %>


  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
     Year<br />
    <%= f.select :year, [2012,2013,2014,2015,2106]%>
  </p>
  <p>
    Status<br />
    <%= f.select :status, [["draft",0],["review",1],["final",2]]%>
  </p>
  <p>
  Hat Area: <br/>
  <%=area_choices("schedule") %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows=>4%>
  </p>
  <p>
    <%= f.label :start %><br />
    <%= f.date_select :start %>
  </p>
  <p>
    <%= f.label :end %><br />
    <%= f.date_select :end %>
  </p>
  <p>
    <%= f.label :shiftlength %><br />
    <%= f.select :shiftlength, [2,3,4,5] %>hours
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', schedules_path %>
</div>
</div>

app/views/schedules/print.html.erb
<div id="thetable">
 <table border="1" >
 <td><%=@schedule.year %></td>
 <%=timeheader(@tms)%>
 
  <% @ppl_sh_s.each do |k|  %>
 
 <tr class="<%=cycle('list-line-even','list-line-odd')%>"> <%=vol_row(k,@ppl_sh[k],@tms)%></tr>

<% end %>
 
 </table>
 
</div>

app/views/schedules/print2.html.erb
<div id="thetable">
 
<table border="1" >
  <tr style="background-color: lightgreen;" > <td><%=@schedule.year %></td> <% @locations.each do |l| %><th width="40"><%=l.name%></th><% end %> </tr>
    <span class="sched-form-button" >
  <% @shift_days.keys.each do |d| %>  
	<tr><th style="background-color: green; color: white" colspan=<%=@x%>><%= @shift_days[d][0].start.strftime("%a, %b %d, %Y") %></th></tr>
	<% shift_hours=@shift_days[d].group_by{|x| x.start.hour} %>
	<% shift_hours.keys.each do |t| %>
		<tr class="<%=cycle('list-line-even','list-line-odd')%>"> <th style="background-color: lightgreen;" ><%= shift_hours[t][0].start.strftime("%I %p")%></th>
		<% shift_hours[t].each do |loc|%>
		          <% name=' ' %>
			  <% name=loc.volunteer.name if !loc.volunteer.nil?%>
			<td><span class="sched-form-button" ><%= name%></span></td>
     
     
		<%end%></tr>

	<% end %>
  <% end %>
  </table>
 
</div>

app/views/schedules/show.html.erb
<div id="schedule">
<h1> <%=h @schedule.title %> / <%=h status(@schedule.status) %> / Shifts assigned: <%=h @n_assigned %> <span class="buttons" ><%= button_to 'Assign Shifts', url_for(:action=> 'assign', :id=>@schedule.id), :method => 'get' if @schedule.status!=2 %></span></h1>

<h3> Key view / Each row shows a key volunteer's shifts. <span class="buttons"><%= button_to 'Print', url_for(:action => :print, :id => @schedule.id), :method => 'get'%>
<%= button_to 'Save', url_for(:action => :save, :id => @schedule.id), :method => 'get' %></span>
</h3>
<p>  
  <%=h @schedule.description %>
</p>


<%= @message %>
 
 
 
 <!-- Each row is a volunteer -->
 <table>
	<%= timeheader(@tms)%>
   	<% @ppl_sh_s.each do |k|  %>
 	<%= vol_row(k,@ppl_sh[k],@tms)%>
	<% end %>
  </table>
 
 <!-- Each row is a timeslot -->
 <h3> Hat view / Each row shows who's on that time <span class="buttons"><%= button_to 'Print', :controller => :schedules, :action => :print2, :id => @schedule.id %><%= button_to 'Save', :controller => :schedules, :action => :save2, :id => @schedule.id %></span></h3>

<!--
<table >
  <tr class="locations" > <td><%=h @schedule.year%></td> 
	<% @locations.each do |l| %>
		<th width="40"><%=l.name%></th>
	<% end %> 
  </tr>
    <span class="sched-form-button" >
<% shift=@shifts[0] %>
<% i=0 %>
  <% @schedule.shifttimes_per_day.each do |d| %>  
	<tr><th class="days" colspan=<%=@x%>><%= shift.start.localtime.strftime("%a %b %d, %Y") %></th></tr>
	<% d.each do |t| %>
		<tr> <td class="times"><%= @shifts[i].start.localtime.strftime("%l%p").downcase %></th>
		<% @schedule.locations.each do |loc|%>
		          <% name=' ' %>
			  <% name=shift.volunteer.name if shift.volunteer %>
			<td><span class="sched-form-button" ><%= name%></span></td>
			<%i=i+1%>
			<%shift=@shifts[i]%>
		<%end%></tr>
	<% end %>
  <% end %>
  </table>
-->
<table border="1" >
  <tr class="locations" > <td/> <% @locations.each do |l| %><th width="40"><%=l.name%></th><% end %> </tr>
  <% @shift_days.keys.each do |d| %>
        <tr><th class="days" colspan=<%=@x%>><%= @shift_days[d][0].start.strftime("%a, %b %d, %Y") %></th></tr>
        <% shift_hours=@shift_days[d].group_by{|x| x.start.hour} %>
        <% shift_hours.keys.each do |t| %>
                <tr> <th class="times" ><%= shift_hours[t][0].start.localtime.strftime("%I %p")%></th>
                <% shift_hours[t].each do |loc|%>
                          <% name=' ' %>
                          <% name=loc.volunteer.name if loc.volunteer%>
                          <% bname='button'+loc.id.to_s() %>
                        <td><%= name %></td>
                <%end%></tr>
        <% end %>
  <% end %>

</table>


<%= link_to 'Back', schedules_path %>

</div>