config/routes.rb
Blueboxes::Application.routes.draw do

  root :to => 'admin#index'
  resources :comments
  resources :signups
  resources :pictures
  resources :areas
  resources :schedules
  resources :locations
  resources :shifts
  get 'volunteers/email' => 'volunteers#email'
  resources :volunteers
  get 'prefs' => 'prefs#index'
  get 'volunteers/prefs' => 'volunteers#prefs'
  match 'volunteers/edit_pw/:id' => 'volunteers#edit_pw'
  match 'volunteers/print_list' => 'volunteers#print_list'
  match 'home/set_vol/:id/:schedule' => 'home#set_vol'
  get 'home' => 'admin#index'
  get 'home/slotPerson2' => 'home#slotPerson2'
  get 'home/slots/:schedule' => 'home#slots'
  get 'gate/duties' => 'gate#message'
  get 'admin/index' => 'admin#index'
  match 'admin/login' => 'admin#login'
  match 'admin/logout' => 'admin#logout'
  get 'admin/bkup' => 'admin#bkup'
  get 'admin/stats' => 'admin#stats'
  match 'admin/set_area/:id' => 'admin#set_area'
  match 'admin/unset_area' => 'admin#unset_area'
  get 'admin/profile' => 'admin#profile'
  get 'gallery' => 'gallery#index'
  get 'gallery/picture/:id' => 'gallery#picture'
  get 'schedules/duplicate/:id' => 'schedules#duplicate'
  post 'schedules/copy/:id' => 'schedules#copy'
  match 'schedules/assign/:id' => 'schedules#assign'
  get 'schedules/print/:id' => 'schedules#print'
  get 'schedules/save/:id' => 'schedules#save'
  get 'schedules/save2/:id' => 'schedules#save2'
  get 'schedules/print2/:id' => 'schedules#print2'
  match 'schedules/update_shift/:id/:vol' => 'schedules#update_shift'
  match 'schedules/do_work/:id' => 'schedules#do_work'
  match 'schedules/do_jswork/:id' => 'schedules#do_jswork'
  match 'news' => 'news#index'
  match 'news/new_entry' => 'news#new_entry'


  #map.connect "home/assign/:schedule", :controller => 'home', :action => 'assign'
  #map.connect "gate/duties", :controller => 'gate', :action => 'duties'


  # See how all your routes lay out with "rake routes"

end

app/controllers/home_controller.rb
require 'my_lib.rb'

class HomeController < ApplicationController
  
  def index
    
     @count_2011 = Volunteer.where("tickets>0 and hat=='f'").size
     @keycount= Signup.find_all_by_year(Date.today.year)
     @sleeps_2011 = Date.new(2011,7,29) - Date.today 
     @sleeps_2012 = Date.new(2012,8,3) - Date.today
      
  end


 
 def getData
     @sched2010=Schedule.find_by_title("Parking2010")
     @allV = Volunteer.all
     @nShifts=@shifttimes.size
     #render(:file=>"c:\\temp\\schedule.csv")
     p=make_file
     #send_file("c:\\temp\\schedule.csv")
     render(:text=>p)
  end
  
  
  
 

  def timetable
    if request.post?
    		 logger.info("Params from timetable... "+params.to_s)
 	@shifts=params[:shift]
      Shift.update(params[:shift].keys, params[:shift].values)
    end
    @locations=Location.all
    @volunteers=Volunteer.all
  end
  
  def paste
    @message = "pasting "+params[:volunteer_id]
  end

  def add_vol_to_shift
  	@volunteer = Volunteer.find(params[:arg1])
  end

  def method_missing(name, *args)
 	render(:inline => %{
 		<h2>Unknown action: #{name} </h2>
 		<%= debug(params) %>
 	})
  end
  
  
  private
 def authorize
  end

  def next_volunteer
  end
 
 def initialize
 
  end

  
 
 def make_file
  cr="<br/>"
  @sched_file=','
    
    for t in @shifttimes
      @sched_file+=t.strftime("%a,")
    end
    @sched_file+=cr
    
    @sched_file+=","
    for t in @shifttimes
      @sched_file+=t.strftime("%l%P,")
    end
    @sched_file+=cr

    @allV.each do |v|
     vlocs = display_by_volunteer(v)
     @sched_file+=v.name
     @sched_file+=", "
     for loc in vlocs do
        @sched_file+=loc
        @sched_file+=","
     end
    @sched_file+=cr
    end
    
    @sched_file+=","
    for t in @shifttimes
      @sched_file+=t.strftime("%a,")
    end
    @sched_file+=cr
    
    @sched_file+=","
    for t in @shifttimes
      @sched_file+=t.strftime("%l%P,")
    end
    @sched_file+=cr

  @sched_file
  end #make_file

 def sched2010
    @sched2010 
  end
  def sched_file
    @sched_file 
  end

 
  
   def set_vol
    if request.post? 
 		 logger.info("Params from set_vol... "+params.to_s)
            
      @volunteer = Volunteer.find(params[:id])
      render (nil)
      #redirect_to :action => 'assign'
      # :schedule=>params[:schedule], :id=>params[:id]
    end
  end
  
end

app/views/home/_schedule.html.erb
<div id="product-list">
<%=h @message %>


Last updated: <%=h @sched2010.updated_at.strftime("%a %b %d %I%p") %>

<p/>

<% daycolor="red" %>
<% daynames = ["THU","FRI", "SAT", "SUN","MON"] %>

<% nslots = [3,7,7,7,3] %>
<% i1=0 
   i2=i1+nslots[0]
   d=0
%>

<% nslots.each do |n| %>
  <% i2=i1+n-1 %>
  <table border="1" >
  <tr>
   <th style="background-color: <%= daycolor %>"><%= daynames[d] %></th>
    <% d=d+1 %>
    <% for t in @shifttimes[i1..i2] %>
      <th><%= t.strftime("%l%P") %></th>
    <% end %>
  </tr>
  <% lgroups = @sched2010.shifts.group_by {|shift| shift.location} %>
  <% lgroups.keys.each do |l| %>
     <%  w=lgroups[l].sort_by { |x| x[:start] }%>
     <tr class="<%= cycle('list-line-odd', 'list-line-even') %>">
     <td><%=l.name%></td>
       
     <% w[i1..i2].each do |sh| %>
    	  <td><%=h sh.volunteer.name[0,5] if sh.volunteer%></td>
     <% end %>
     </tr>
  <% end %>
  </table>
  
<% i1=i2+1 %> 
<% end %>

</div>

<!--sh.volunteer.name.initial_caps -->

app/views/home/index.html.erb
<div id="home">
<h1>Welcome New and Returning Keys!</h1>
<p style="text-align:center"><span class="b"> Only <%=sleeps%> more sleeps until BLUE SKIES!</span>

<p>
Time to sign up for 2013 by going to your profile and signup and specify number of tickets required.
</p>
<ul>
<li>First dibs go to last year's keys and sabbatical hats</li>
<li>Login, click on your hat area, signup by Feb 15</li>
<li>Update your password and contact info</li>
<li>Update your availability and ideal times/spots. Let me know the earliest time you can start on Thursday (2pm is the first)</li>
<li>When schedule status is "review", please review your shifts and</li>
<ul>
<li>login and post a public change request </li>
<li>you can login and get the current email list if necessary for privacy</li>
<li>using the postings page will inspire collaboration and alleviate hat bottleneck</li>
</ul>
</ul>
<% if session[:isHat] %>
<ul>
<li>Database schema</li>

<ul>
<li><%= link_to 'News', comments_path%></li>
<li><%= link_to 'Hat Areas', areas_path %></li>
<li><%= link_to 'Volunteers', volunteers_path%></li> 
<li><%= link_to 'Locations', locations_path%></li>
<li>location_schedules</li>  
<li><%= link_to 'Pictures', pictures_path%></li>  
<li><%= link_to 'Schedules', schedules_path%></li> 
<li><%= link_to 'Shifts', shifts_path%></li>  
<li><%= link_to 'Signups', signups_path%></li>  
</ul>
<li>Pages</li>
<ul>
<li><%= link_to 'News', :controller=>'news'%></li>
<li><%= link_to 'Email', :controller=>'volunteers', :action=>'email' %></li>
<li><%= link_to 'Tickets', :controller=>'admin', :action=>'stats' %></li>
</ul>
</ul>
<% else %>

<p>Pages</p>
<ul>
<li><%= link_to 'News', :controller=>'news'%></li>
<li><%= link_to 'Email', :controller=>'volunteers', :action=>'email' %></li>
</ul>

<% end %>


<p style="text-align:center"> <%=link_to car_disp, :controller=>'admin'%></p>

</div>
<!--
<p style="text-align:center"> <span class="c">We have 3 hats, 1 apprentice and <%=@keycount%> keys signed up for 2013! </span></p>

<h2>2012 schedule</h2>

<div class="home-button" >
<%= button_to 'Download', :controller => :parking, :action => :save %>
</div>


-->

app/views/home/print.html.erb
<h1>Print</h1>
1. Grab a screenshot of the <%= button_to 'Schedule', :controller => :parking %> OR<br>
2. You can get the latest data here for putting into your own formatted spreadsheet<br>
Suggestion: paste the data to Excel. Data > Text to columns to separate by commas. <%= button_to 'Show Raw Data', :controller => :parking, :action => :getData %>
OR<br>
3. You can get my formatted excel spreadsheet here but it may not have the latest data (check the date): <%= button_to 'Download Formatted', :controller => :parking, :action => :save %>

app/views/home/timetable.html.erb
<div id="product-list">
<h1>Parking Schedule</h1>
<%=h @message %>

<%= render :partial => 'schedule'  %>