config/routes.rb
Blueboxes::Application.routes.draw do

  root :to => 'admin#index'
  resources :comments
  resources :signups
  resources :pictures
  resources :areas
  resources :schedules
  resources :locations
  resources :shifts
  get 'volunteers/email' => 'volunteers#email'
  resources :volunteers
  get 'prefs' => 'prefs#index'
  get 'volunteers/prefs' => 'volunteers#prefs'
  match 'volunteers/edit_pw/:id' => 'volunteers#edit_pw'
  match 'volunteers/print_list' => 'volunteers#print_list'
  match 'home/set_vol/:id/:schedule' => 'home#set_vol'
  get 'home' => 'admin#index'
  get 'home/slotPerson2' => 'home#slotPerson2'
  get 'home/slots/:schedule' => 'home#slots'
  get 'gate/duties' => 'gate#message'
  get 'admin/index' => 'admin#index'
  match 'admin/login' => 'admin#login'
  match 'admin/logout' => 'admin#logout'
  get 'admin/bkup' => 'admin#bkup'
  get 'admin/stats' => 'admin#stats'
  match 'admin/set_area/:id' => 'admin#set_area'
  match 'admin/unset_area' => 'admin#unset_area'
  get 'admin/profile' => 'admin#profile'
  get 'gallery' => 'gallery#index'
  get 'gallery/picture/:id' => 'gallery#picture'
  get 'schedules/duplicate/:id' => 'schedules#duplicate'
  post 'schedules/copy/:id' => 'schedules#copy'
  match 'schedules/assign/:id' => 'schedules#assign'
  get 'schedules/print/:id' => 'schedules#print'
  get 'schedules/save/:id' => 'schedules#save'
  get 'schedules/save2/:id' => 'schedules#save2'
  get 'schedules/print2/:id' => 'schedules#print2'
  match 'schedules/update_shift/:id/:vol' => 'schedules#update_shift'
  match 'schedules/do_work/:id' => 'schedules#do_work'
  match 'schedules/do_jswork/:id' => 'schedules#do_jswork'
  match 'news' => 'news#index'
  match 'news/new_entry' => 'news#new_entry'


  #map.connect "home/assign/:schedule", :controller => 'home', :action => 'assign'
  #map.connect "gate/duties", :controller => 'gate', :action => 'duties'


  # See how all your routes lay out with "rake routes"

end

app/models/shift.rb
class Shift < ActiveRecord::Base
  belongs_to :location
  belongs_to :volunteer
  belongs_to :schedule

def self.find_shifts_at(loc)
  Shift.find_all(:location_id => loc.id) 
end
def self.find_shift(loc, time)
  #Shift.find(:first, :conditions => ["location_id = ? and start = ?", loc.id, time]) 
  Shift.where(:location_id => loc.id, :start => time).first
end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
	before_filter :check_admin
  # GET /shifts
  # GET /shifts.xml
  def index
    @shifts = Shift.all
    #@locations = {'Gate', 'P1', 'Inner', 'Performer'}
    #@shifts_at_P1 = Shift.find_shifts_at(Location.find_by_name("P1"))
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @shifts }
    end
  end
 
  # GET /shifts/1
  # GET /shifts/1.xml
  def show
    @shift = Shift.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @shift }
    end
  end

  # GET /shifts/new
  # GET /shifts/new.xml
  def new
    @shift = Shift.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @shift }
    end
  end

  # GET /shifts/1/edit
  def edit
    @shift = Shift.find(params[:id])
  end

  # POST /shifts
  # POST /shifts.xml
  def create
    @shift = Shift.new(params[:shift])

    respond_to do |format|
      if @shift.save
        flash[:notice] = 'Shift was successfully created.'
        format.html { redirect_to(@shift) }
        format.xml  { render :xml => @shift, :status => :created, :location => @shift }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @shift.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shifts/1
  # PUT /shifts/1.xml
  def update
    @shift = Shift.find(params[:id])

    respond_to do |format|
      if @shift.update_attributes(params[:shift])
        flash[:notice] = 'Shift was successfully updated.'
        format.html { redirect_to(@shift) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @shift.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.xml
  def destroy
    @shift = Shift.find(params[:id])
    @shift.destroy

    respond_to do |format|
      format.html { redirect_to(shifts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/edit.html.erb
<h1>Editing shift</h1>
Don't edit start or location!
<%= form_for(@shift) do |f| %>
 <% @area.shift.full_messages.each do |msg| %>
      <p><%= msg %></p>
   <% end %>


  <p>
    <%= f.label :start %><br />
    <!--%= f.datetime_select :start %-->
  </p>
  <p>
    <%= f.label :location %><br />
    <!--%= f.text_field :location %-->
  </p>
 <p>
    <%= f.label :volunteer %><br />
    <%= select(:shift, "volunteer_id", Volunteer.all.collect{ |v| [ v.name, v.id]}) %> 
  </p>

  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

app/views/shifts/index.html.erb
<h1>Listing shifts</h1>

<table>
  <tr>
<th>Id</th>

    <th>Start</th>
    <th>Location</th>
 <th>Volunteer</th>
<th>Schedule</th>


  </tr>

<% @shifts.each do |shift| %>
  <tr>
<td><%=h shift.id %>
    <td><%=h shift.start.strftime("%a %b %d %I%p") if shift.start %></td>
    <td><%=h shift.location.name if shift.location%></td>
 <td><%=h shift.volunteer.name if shift.volunteer%></td>
<td><%=h shift.schedule.title if shift.schedule%></td>


    <td><%= link_to 'Show', shift %></td>
    <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
    <td><%= link_to 'Destroy', shift, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New shift', new_shift_path %>

app/views/shifts/new.html.erb
<h1>New shift</h1>

<%= form_for(@shift) do |f| %>
 <% @shift.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
   <% end %>


  <p>
    <%= f.label :start %><br />
    <%= f.datetime_select :start %>
  </p>
  <p>
    <%= f.label :location %><br />
<%= select("shift", "location_id", Location.all.collect{ |loc| [ loc.name, loc.id] }) %>
     <%= link_to 'New location', locations_path %>
<p>
   
<%= f.label :volunteer %><br />
<%= select("shift", "volunteer_id", Volunteer.all.collect{ |v| [ v.name, v.id] }, {:include_blank => 'nobody'}) %>
<%= link_to 'New volunteer', volunteers_path %>
</p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', shifts_path %>

app/views/shifts/show.html.erb
<p>
  <b>Start:</b>
  <%=h @shift.start %>
</p>

<p>
  <b>Location:</b>
  <%=h @shift.location.name if @shift.location %>
</p>

<p>
  <b>Volunteer:</b>
  <%=h @shift.volunteer.name if @shift.volunteer %>
</p>



<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %>