config/routes.rb
Blueboxes::Application.routes.draw do

  root :to => 'admin#index'
  resources :comments
  resources :signups
  resources :pictures
  resources :areas
  resources :schedules
  resources :locations
  resources :shifts
  get 'volunteers/email' => 'volunteers#email'
  resources :volunteers
  get 'prefs' => 'prefs#index'
  get 'volunteers/prefs' => 'volunteers#prefs'
  match 'volunteers/edit_pw/:id' => 'volunteers#edit_pw'
  match 'volunteers/print_list' => 'volunteers#print_list'
  match 'home/set_vol/:id/:schedule' => 'home#set_vol'
  get 'home' => 'admin#index'
  get 'home/slotPerson2' => 'home#slotPerson2'
  get 'home/slots/:schedule' => 'home#slots'
  get 'gate/duties' => 'gate#message'
  get 'admin/index' => 'admin#index'
  match 'admin/login' => 'admin#login'
  match 'admin/logout' => 'admin#logout'
  get 'admin/bkup' => 'admin#bkup'
  get 'admin/stats' => 'admin#stats'
  match 'admin/set_area/:id' => 'admin#set_area'
  match 'admin/unset_area' => 'admin#unset_area'
  get 'admin/profile' => 'admin#profile'
  get 'gallery' => 'gallery#index'
  get 'gallery/picture/:id' => 'gallery#picture'
  get 'schedules/duplicate/:id' => 'schedules#duplicate'
  post 'schedules/copy/:id' => 'schedules#copy'
  match 'schedules/assign/:id' => 'schedules#assign'
  get 'schedules/print/:id' => 'schedules#print'
  get 'schedules/save/:id' => 'schedules#save'
  get 'schedules/save2/:id' => 'schedules#save2'
  get 'schedules/print2/:id' => 'schedules#print2'
  match 'schedules/update_shift/:id/:vol' => 'schedules#update_shift'
  match 'schedules/do_work/:id' => 'schedules#do_work'
  match 'schedules/do_jswork/:id' => 'schedules#do_jswork'
  match 'news' => 'news#index'
  match 'news/new_entry' => 'news#new_entry'


  #map.connect "home/assign/:schedule", :controller => 'home', :action => 'assign'
  #map.connect "gate/duties", :controller => 'gate', :action => 'duties'


  # See how all your routes lay out with "rake routes"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	validates_presence_of :comment, :name, :content_type,  :message => "must specify a file"
	#validates_format_of :content_type, :with => /^image/, :message => "... you can only upload pictures"
	
	#validates_length_of :data, :maximum=>100.kilobytes, :message=>"less than %d if you don't mind"
	def self.upload_dir
    # create a directory: public/images/uploads
    Rails.root.join('public', 'images', 'uploads')
  end
	def uploaded_picture=(picture_field)
		return if picture_field.nil?
		self.name=base_part_of(picture_field.original_filename)
		self.content_type=picture_field.content_type.chomp
		#self.data=picture_field.read
		# create a migration to add this column
    		self.path         = File.join(Picture.upload_dir, "#{self.name}")
		#File.join(Picture.upload_dir, "#{self.id}.#{extension(picture_field.original_filename)}")
	
	
	# write the file to the path
	File.open(self.path, "wb") {|f| f.write(picture_field.read)}
	end

  def base_part_of(file_name)
    File.basename(file_name).gsub(/[^\w._-]/, '')
  end
  
  def extension(file_name)
    File.extname(file_name)
  end
	
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # GET /pictures
  # GET /pictures.xml
  def index
    @pictures = Picture.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.xml
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.xml
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.xml
  def create
    @picture = Picture.new(params[:picture])

    respond_to do |format|
      if @picture.save
        flash[:notice] = 'Picture was successfully created.'
        format.html { redirect_to(@picture) }
        format.xml  { render :xml => @picture, :status => :created, :location => @picture }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @picture.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.xml
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        flash[:notice] = 'Picture was successfully updated.'
	expire_page :controller=>'gallery'
        format.html { redirect_to(@picture) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @picture.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.xml
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to(pictures_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= form_for(@picture) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <tr>
  <th>ID</th>
    <th>Name</th>
    <th>Comment</th>
  </tr>

<% @pictures.each do |picture| %>
  <tr>
  <td><%=h picture.id %></td>
    <td><%=h picture.name %></td>
    <td><%=h picture.comment %></td>
    <td><%= link_to 'Show', picture %></td>
    <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
    <td><%= link_to 'Destroy', picture, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= form_for(@picture) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p>
  <b>Name:</b>
  <%=h @picture.name %>
</p>

<p>
  <b>Comment:</b>
  <%=h @picture.comment %>
</p>


<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>